[config]
schemaVersion = "0.0.1"

[package]
namespace = "gogas1"
name = "LookingAroundKBM"
versionNumber = "0.1.0"
description = "Allows to look around using keyboard and mouse"
websiteUrl = "link to the git repo"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-BepinExConfigurationManager" = "18.3.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
